#!/usr/bin/bash

disconnected=""
vpn_connected=""
SUCCESS="Connected"

while true; do
    if [[ $(timeout -s KILL 0.5 mullvad status | grep status) == *$SUCCESS* ]]
    then
        echo "$vpn_connected" ; sleep 2
    else
        echo "$disconnected" ; sleep 2
    fi
done
